#!/bin/bash

load inquirer

check() {
  if [ ! -f $SERVICE_CONFIG ]; then
     touch $SERVICE_CONFIG
  fi
  config::load_file $SERVICE_CONFIG

  if [ -z "$SERVICE_NPC_SERVER" ]; then
    inquirer::text "请输入 SERVICE_NPC_SERVER:" value
    config::set SERVICE_NPC_SERVER $value $SERVICE_CONFIG
  fi

  if [ -z "$SERVICE_NPC_KEY" ]; then
    inquirer::text "请输入 SERVICE_NPC_KEY:" value
    config::set SERVICE_NPC_KEY $value $SERVICE_CONFIG
  fi

  # load again
  config::load_file $SERVICE_CONFIG
  
  # @TODO
  export SERVICE_NPC_SERVER=$SERVICE_NPC_SERVER
  export SERVICE_NPC_KEY=$SERVICE_NPC_KEY
}

check $@
