#!/bin/bash

load inquirer

check() {
  if [ ! -f $SERVICE_CONFIG ]; then
     touch $SERVICE_CONFIG
  fi
  config::load_file $SERVICE_CONFIG

  if [ -z "$SERVICE_NPC_HOST" ]; then
    inquirer::text "请输入 SERVICE_NPC_HOST:" value
    config::set SERVICE_NPC_HOST $value $SERVICE_CONFIG
  fi

   if [ -z "$SERVICE_NPC_PORT" ]; then
    inquirer::text "请输入 SERVICE_NPC_PORT:" value
    config::set SERVICE_NPC_PORT $value $SERVICE_CONFIG
  fi

  if [ -z "$SERVICE_NPC_KEY" ]; then
    inquirer::text "请输入 SERVICE_NPC_KEY:" value
    config::set SERVICE_NPC_KEY $value $SERVICE_CONFIG
  fi

  # load again
  config::load_file $SERVICE_CONFIG
  
  # @TODO
  export SERVICE_NPC_HOST=$SERVICE_NPC_HOST
  export SERVICE_NPC_PORT=$SERVICE_NPC_PORT
  export SERVICE_NPC_KEY=$SERVICE_NPC_KEY
}

check $@
