version: '3.7'

services:
  npc:
    restart: always
    image: whatwewant/npc:${SERVICE_NPS_VERSION}
    # network_mode: host
    # network_mode: bridge
    environment:
      TZ: Asia/Shanghai
      SERVER: ${SERVICE_NPC_HOST}:${SERVICE_NPC_PORT}
      KEY: ${SERVICE_NPC_KEY}

networks:
  default:
    external: true
    name: compose-ingress
